name: Automatic deployment ✨

on:
  # Trigger workflow when pushing to "dev"
  push:
    branches:
      - dev

  # Add manual triggers too
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Build and Deploy
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "Publisher O.o"
          npx ng deploy --base-href=/${{ github.event.repository.name }}/ --no-silent
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
